var hierarchy =
[
    [ "KeepItFit___Project_WinUI.ViewModel.AddExerciseViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_add_exercise_view_model.html", null ],
    [ "Application", null, [
      [ "KeepItFit___Project_WinUI.App", "class_keep_it_fit_______project___win_u_i_1_1_app.html", null ]
    ] ],
    [ "global.MicrosoftUI.Xaml.Application", null, [
      [ "KeepItFit___Project_WinUI.App", "class_keep_it_fit_______project___win_u_i_1_1_app.html", null ]
    ] ],
    [ "KeepItFit___Project_WinUI.ViewModel.AvatarViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_avatar_view_model.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchCardioExercise.CardioCreation", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_cardio_exercise_1_1_cardio_creation.html", null ],
    [ "KeepItFit___Project_WinUI.ViewModel.DeleteAccountViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_delete_account_view_model.html", null ],
    [ "KeepItFit___Project_WinUI.MainWindow.EncourageSentence", "class_keep_it_fit_______project___win_u_i_1_1_main_window_1_1_encourage_sentence.html", null ],
    [ "KeepItFit___Project_WinUI.View.AddExercisePage.IAddExercisePage_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_exercise_page_1_1_i_add_exercise_page___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.View.AddExercisePage.IAddExercisePage_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_exercise_page_1_1_i_add_exercise_page___bindings_scope_connector.html", null ],
    [ "KeepItFit___Project_WinUI.View.AddFood.IAddFood_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_food_1_1_i_add_food___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.View.AddFood.IAddFood_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_food_1_1_i_add_food___bindings_scope_connector.html", null ],
    [ "KeepItFit___Project_WinUI.View.ChangePasswordPage.IChangePasswordPage_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_change_password_page_1_1_i_change_password_page___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.View.ChangePasswordPage.IChangePasswordPage_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_change_password_page_1_1_i_change_pas4191c2a5ea6cad905dd7d70261b8d161.html", null ],
    [ "KeepItFit___Project_WinUI.View.CreateMyFood.ICreateMyFood_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_create_my_food_1_1_i_create_my_food___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.View.CreateMyFood.ICreateMyFood_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_create_my_food_1_1_i_create_my_food___bindings_scope_connector.html", null ],
    [ "KeepItFit___Project_WinUI.Services.IDao", "interface_keep_it_fit_______project___win_u_i_1_1_services_1_1_i_dao.html", [
      [ "KeepItFit___Project_WinUI.Services.MockDAO", "class_keep_it_fit_______project___win_u_i_1_1_services_1_1_mock_d_a_o.html", null ],
      [ "KeepItFit___Project_WinUI.Services.SQLDao", "class_keep_it_fit_______project___win_u_i_1_1_services_1_1_s_q_l_dao.html", null ]
    ] ],
    [ "KeepItFit___Project_WinUI.ExercisePage.IExercisePage_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_exercise_page_1_1_i_exercise_page___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.ExercisePage.IExercisePage_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_exercise_page_1_1_i_exercise_page___bindings_scope_connector.html", null ],
    [ "KeepItFit___Project_WinUI.FoodDiary.IFoodDiary_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_food_diary_1_1_i_food_diary___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.FoodDiary.IFoodDiary_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_food_diary_1_1_i_food_diary___bindings_scope_connector.html", null ],
    [ "KeepItFit___Project_WinUI.FoodPage.IFoodPage_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_food_page_1_1_i_food_page___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.FoodPage.IFoodPage_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_food_page_1_1_i_food_page___bindings_scope_connector.html", null ],
    [ "KeepItFit___Project_WinUI.MainWindow.IMainWindow_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_main_window_1_1_i_main_window___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.MainWindow.IMainWindow_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_main_window_1_1_i_main_window___bindings_scope_connector.html", null ],
    [ "INotifyPropertyChanged", null, [
      [ "KeepItFit___Project_WinUI.Model.CardioExercise", "class_keep_it_fit_______project___win_u_i_1_1_model_1_1_cardio_exercise.html", null ],
      [ "KeepItFit___Project_WinUI.Model.Food", "class_keep_it_fit_______project___win_u_i_1_1_model_1_1_food.html", null ],
      [ "KeepItFit___Project_WinUI.Model.InputNutritionData", "class_keep_it_fit_______project___win_u_i_1_1_model_1_1_input_nutrition_data.html", null ],
      [ "KeepItFit___Project_WinUI.Model.Meals", "class_keep_it_fit_______project___win_u_i_1_1_model_1_1_meals.html", null ],
      [ "KeepItFit___Project_WinUI.Model.Nutritions", "class_keep_it_fit_______project___win_u_i_1_1_model_1_1_nutritions.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.AddFoodViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_add_food_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.ChangePasswordPageViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_change_password_page_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.CreateMyFoodViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_create_my_food_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.ExercisePageViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_exercise_page_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.FoodDiaryViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_food_diary_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.FoodPageViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_food_page_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.NutritionsViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_nutritions_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.SearchExerciseViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_search_exercise_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.SearchFoodViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_search_food_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.SignInViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_sign_in_view_model.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.SignUpViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_sign_up_view_model.html", null ]
    ] ],
    [ "KeepItFit___Project_WinUI.ViewModel.InputExerciseViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_input_exercise_view_model.html", null ],
    [ "KeepItFit___Project_WinUI.ViewModel.InputNutritionViewModel", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_input_nutrition_view_model.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchCardioExercise.ISearchCardioExercise_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_cardio_exercise_1_1_i_search_cardio_exercise___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchCardioExercise.ISearchCardioExercise_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_cardio_exercise_1_1_i_search_cdf2bbabe3c3f01d50f46b294208c04ef.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchFood.ISearchFood_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_food_1_1_i_search_food___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchFood.ISearchFood_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_food_1_1_i_search_food___bindings_scope_connector.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchStrengthTrainingExercise.ISearchStrengthTrainingExercise_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_strength_training_exercise_1_16f887d3eb2922adc60b0ef32743697f5.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchStrengthTrainingExercise.ISearchStrengthTrainingExercise_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_strength_training_exercise_1_157b7ff51acfc86639c6994d3a797f700.html", null ],
    [ "KeepItFit___Project_WinUI.View.SignIn.ISignIn_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_sign_in_1_1_i_sign_in___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.View.SignIn.ISignIn_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_sign_in_1_1_i_sign_in___bindings_scope_connector.html", null ],
    [ "KeepItFit___Project_WinUI.View.SignUp.ISignUp_Bindings", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_sign_up_1_1_i_sign_up___bindings.html", null ],
    [ "KeepItFit___Project_WinUI.View.SignUp.ISignUp_BindingsScopeConnector", "interface_keep_it_fit_______project___win_u_i_1_1_view_1_1_sign_up_1_1_i_sign_up___bindings_scope_connector.html", null ],
    [ "IValueConverter", null, [
      [ "KeepItFit___Project_WinUI.ViewModel.TimeToCaloriesBurnedConverter", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_time_to_calories_burned_converter.html", null ],
      [ "KeepItFit___Project_WinUI.ViewModel.ValueToColorConverter", "class_keep_it_fit_______project___win_u_i_1_1_view_model_1_1_value_to_color_converter.html", null ]
    ] ],
    [ "KeepItFit___Project_WinUI.View.AddFood.NavigationParameters_AddFood_MyFood_ToSearchFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_food_1_1_navigation_parameters___add_food___my_food___to_search_food.html", null ],
    [ "KeepItFit___Project_WinUI.View.AddFood.NavigationParameters_AddFood_RecentOrFrequent_ToFoodDiary", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_food_1_1_navigation_parameters___add_9e11cb0cb9e25d47839a8015036effb8.html", null ],
    [ "KeepItFit___Project_WinUI.View.AddFood.NavigationParameters_AddFood_ToSearchFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_food_1_1_navigation_parameters___add_food___to_search_food.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchFood.NavigationParameters_SearchFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_food_1_1_navigation_parameters___search_food.html", null ],
    [ "KeepItFit___Project_WinUI.ExercisePage.Navigations", "class_keep_it_fit_______project___win_u_i_1_1_exercise_page_1_1_navigations.html", null ],
    [ "global.MicrosoftUI.Xaml.Controls.Page", null, [
      [ "KeepItFit___Project_WinUI.ExercisePage", "class_keep_it_fit_______project___win_u_i_1_1_exercise_page.html", null ],
      [ "KeepItFit___Project_WinUI.FoodDiary", "class_keep_it_fit_______project___win_u_i_1_1_food_diary.html", null ],
      [ "KeepItFit___Project_WinUI.FoodPage", "class_keep_it_fit_______project___win_u_i_1_1_food_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.AddExercisePage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_exercise_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.AddFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_food.html", null ],
      [ "KeepItFit___Project_WinUI.View.ChangePasswordPage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_change_password_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.CreateExercise", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_create_exercise.html", null ],
      [ "KeepItFit___Project_WinUI.View.CreateMyFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_create_my_food.html", null ],
      [ "KeepItFit___Project_WinUI.View.HomePage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_home_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.ReportPage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_report_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.SearchCardioExercise", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_cardio_exercise.html", null ],
      [ "KeepItFit___Project_WinUI.View.SearchFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_food.html", null ],
      [ "KeepItFit___Project_WinUI.View.SearchStrengthTrainingExercise", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_strength_training_exercise.html", null ],
      [ "KeepItFit___Project_WinUI.View.SettingsPage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_settings_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.SignUp", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_sign_up.html", null ]
    ] ],
    [ "Page", null, [
      [ "KeepItFit___Project_WinUI.ExercisePage", "class_keep_it_fit_______project___win_u_i_1_1_exercise_page.html", null ],
      [ "KeepItFit___Project_WinUI.FoodDiary", "class_keep_it_fit_______project___win_u_i_1_1_food_diary.html", null ],
      [ "KeepItFit___Project_WinUI.FoodPage", "class_keep_it_fit_______project___win_u_i_1_1_food_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.AddExercisePage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_exercise_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.AddFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_food.html", null ],
      [ "KeepItFit___Project_WinUI.View.ChangePasswordPage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_change_password_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.CreateExercise", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_create_exercise.html", null ],
      [ "KeepItFit___Project_WinUI.View.CreateMyFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_create_my_food.html", null ],
      [ "KeepItFit___Project_WinUI.View.HomePage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_home_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.ReportPage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_report_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.SearchCardioExercise", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_cardio_exercise.html", null ],
      [ "KeepItFit___Project_WinUI.View.SearchFood", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_food.html", null ],
      [ "KeepItFit___Project_WinUI.View.SearchStrengthTrainingExercise", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_strength_training_exercise.html", null ],
      [ "KeepItFit___Project_WinUI.View.SettingsPage", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_settings_page.html", null ],
      [ "KeepItFit___Project_WinUI.View.SignUp", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_sign_up.html", null ]
    ] ],
    [ "KeepItFit___Project_WinUI.Program", "class_keep_it_fit_______project___win_u_i_1_1_program.html", null ],
    [ "KeepItFit___Project_WinUI.View.AddExercisePage.Query", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_add_exercise_page_1_1_query.html", null ],
    [ "KeepItFit___Project_WinUI.View.SearchStrengthTrainingExercise.StrengthCreation", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_search_strength_training_exercise_1_1_strength_creation.html", null ],
    [ "KeepItFit___Project_WinUI.Model.StrengthTraining", "class_keep_it_fit_______project___win_u_i_1_1_model_1_1_strength_training.html", null ],
    [ "KeepItFit___Project_WinUI.Model.UserInfo", "class_keep_it_fit_______project___win_u_i_1_1_model_1_1_user_info.html", null ],
    [ "KeepItFit___Project_WinUI.Services.UserSessionService", "class_keep_it_fit_______project___win_u_i_1_1_services_1_1_user_session_service.html", null ],
    [ "KeepItFit___Project_WinUI.NutritionResult.ViewModel", "class_keep_it_fit_______project___win_u_i_1_1_nutrition_result_1_1_view_model.html", null ],
    [ "global.MicrosoftUI.Xaml.Window", null, [
      [ "KeepItFit___Project_WinUI.MainWindow", "class_keep_it_fit_______project___win_u_i_1_1_main_window.html", null ],
      [ "KeepItFit___Project_WinUI.NutritionResult", "class_keep_it_fit_______project___win_u_i_1_1_nutrition_result.html", null ],
      [ "KeepItFit___Project_WinUI.View.IntroToApp.Intro", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_intro_to_app_1_1_intro.html", null ],
      [ "KeepItFit___Project_WinUI.View.IntroToApp.UserSurvey", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_intro_to_app_1_1_user_survey.html", null ],
      [ "KeepItFit___Project_WinUI.View.SignIn", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_sign_in.html", null ]
    ] ],
    [ "Window", null, [
      [ "KeepItFit___Project_WinUI.MainWindow", "class_keep_it_fit_______project___win_u_i_1_1_main_window.html", null ],
      [ "KeepItFit___Project_WinUI.NutritionResult", "class_keep_it_fit_______project___win_u_i_1_1_nutrition_result.html", null ],
      [ "KeepItFit___Project_WinUI.View.IntroToApp.Intro", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_intro_to_app_1_1_intro.html", null ],
      [ "KeepItFit___Project_WinUI.View.IntroToApp.UserSurvey", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_intro_to_app_1_1_user_survey.html", null ],
      [ "KeepItFit___Project_WinUI.View.SignIn", "class_keep_it_fit_______project___win_u_i_1_1_view_1_1_sign_in.html", null ]
    ] ]
];